language: minimal

services:
  - docker

script:
  # Build images using docker-compose
  - docker-compose -f docker-compose-build.yaml build --parallel

  # Tag images using DOCKER_USERNAME
  - docker tag udagram-api-feed "$DOCKER_USERNAME/udagram-api-feed:v2"
  - docker tag udagram-api-user "$DOCKER_USERNAME/udagram-api-user:v2"
  - docker tag udagram-frontend "$DOCKER_USERNAME/udagram-frontend:v2"
  - docker tag reverseproxy "$DOCKER_USERNAME/reverseproxy:v2"

after_success:
  # Log in to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push images to DockerHub
  - docker push "$DOCKER_USERNAME/udagram-api-feed:v2"
  - docker push "$DOCKER_USERNAME/udagram-api-user:v2"
  - docker push "$DOCKER_USERNAME/udagram-frontend:v2"
  - docker push "$DOCKER_USERNAME/reverseproxy:v2"

# Optionally, specify which branches to build
branches:
  only:
    - main  # or your specific branch
